import { TooltipProvider } from "@/components/ui/tooltip";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from "./context/AuthContext";
import "./globals.css";
import { Toaster } from 'sonner';

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="dark">
			<head>
				{/* Suppress ElevenLabs/LiveKit SDK internal noise before any bundle loads */}
				<script
					dangerouslySetInnerHTML={{
						__html: `
(function() {
  // Patterns from ElevenLabs/LiveKit SDK that are noise, not real app errors
  var SUPPRESS_PATTERNS = [
    'error_type',
    "reading 'error_type'",
    'Unknown DataChannel error',
    'websocket closed',
    'DataChannel error on reliable',
    'DataChannel error on lossy',
  ];

  function shouldSuppress(msg) {
    if (!msg || typeof msg !== 'string') return false;
    for (var i = 0; i < SUPPRESS_PATTERNS.length; i++) {
      if (msg.indexOf(SUPPRESS_PATTERNS[i]) !== -1) return true;
    }
    return false;
  }

  // Patch console.error so Turbopack overlay doesn't pick these up
  var _origConsoleError = console.error.bind(console);
  console.error = function() {
    var msg = arguments[0];
    var msgStr = typeof msg === 'string' ? msg : (msg && msg.message ? msg.message : '');
    if (shouldSuppress(msgStr)) return;
    return _origConsoleError.apply(console, arguments);
  };

  // Patch unhandledrejection listener wrapping
  var _origAdd = window.addEventListener.bind(window);
  window.addEventListener = function(type, listener, opts) {
    if (type === 'unhandledrejection') {
      var wrapped = function(e) {
        var msg = (e.reason && e.reason.message) || (typeof e.reason === 'string' ? e.reason : '');
        if (shouldSuppress(msg)) { e.preventDefault(); return; }
        return listener.call(this, e);
      };
      return _origAdd(type, wrapped, opts);
    }
    return _origAdd(type, listener, opts);
  };

  // Catch synchronous errors in capture phase
  window.addEventListener('error', function(e) {
    if (e && shouldSuppress(e.message)) { e.preventDefault(); return true; }
  }, true);
})();
`,
					}}
				/>
			</head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<AuthProvider>
					<TooltipProvider>{children}</TooltipProvider>
					<Toaster theme="dark" position="top-right" />
				</AuthProvider>
			</body>
		</html>
	);
}
